inherit_from: ../.rubocop.yml

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Security/MarshalLoad:
  Enabled: false
